#!/bin/bash
# Audit Trail Hooks
# Captures agent delegations, completions, and failures to session logs

# Configuration
AUDIT_DIR=".claude/audit/sessions"
DATE=$(date +%Y-%m-%d)
LOG_FILE="$AUDIT_DIR/$DATE.md"
TIMESTAMP=$(date +%H:%M:%S)
FULL_TIMESTAMP=$(date -Iseconds)

# Ensure audit directory exists
mkdir -p "$AUDIT_DIR"

# Initialize log file if it doesn't exist
if [ ! -f "$LOG_FILE" ]; then
    echo "# Session Log: $DATE" > "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    echo "> Auto-generated by audit-hooks.sh" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
fi

# Get hook event type from environment
HOOK_EVENT="${CLAUDE_HOOK_EVENT:-unknown}"

# Parse input based on event type
case "$HOOK_EVENT" in
    "SubagentStart")
        # Extract agent info from TOOL_INPUT
        AGENT_NAME=$(echo "$TOOL_INPUT" | grep -oP '(?<="subagent_type":")[^"]+' 2>/dev/null || echo "unknown")
        TASK_DESC=$(echo "$TOOL_INPUT" | grep -oP '(?<="description":")[^"]+' 2>/dev/null || echo "")
        PROMPT_PREVIEW=$(echo "$TOOL_INPUT" | grep -oP '(?<="prompt":")[^"]{0,100}' 2>/dev/null || echo "")

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Agent Delegated: $AGENT_NAME

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Agent | $AGENT_NAME |
| Description | $TASK_DESC |
| Task Preview | ${PROMPT_PREVIEW}... |
| Status | In Progress |

EOF
        ;;

    "SubagentStop")
        # Extract completion info
        AGENT_NAME=$(echo "$TOOL_INPUT" | grep -oP '(?<="agent":")[^"]+' 2>/dev/null || echo "unknown")

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Agent Completed: $AGENT_NAME

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Agent | $AGENT_NAME |
| Status | Completed |

EOF
        ;;

    "PostToolUseFailure")
        # Extract failure info
        TOOL_NAME=$(echo "$TOOL_INPUT" | grep -oP '(?<="tool":")[^"]+' 2>/dev/null || echo "unknown")
        ERROR_MSG=$(echo "$TOOL_OUTPUT" | head -c 500 | tr '\n' ' ' | sed 's/|/\\|/g')

        cat >> "$LOG_FILE" << EOF

### $TIMESTAMP - Tool Failed: $TOOL_NAME

| Field | Value |
|-------|-------|
| Timestamp | $FULL_TIMESTAMP |
| Tool | $TOOL_NAME |
| Error | $ERROR_MSG |

EOF
        ;;

    "SessionStart")
        cat >> "$LOG_FILE" << EOF

---

## Session Started: $FULL_TIMESTAMP

EOF
        ;;

    "SessionEnd")
        cat >> "$LOG_FILE" << EOF

## Session Ended: $FULL_TIMESTAMP

---

EOF
        ;;

    *)
        # Unknown event - log for debugging
        echo "### $TIMESTAMP - Unknown Event: $HOOK_EVENT" >> "$LOG_FILE"
        ;;
esac

# Always exit successfully - audit should never block operations
exit 0
